name: Tests wrappers

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * 0'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
            # pin the last stable mamba version because 0.21.1 has bug in github action
            conda install -c conda-forge mamba=0.18.1 --quiet
            mamba create -c bioconda -c conda-forge --quiet -y --name snakemake snakemake-minimal pytest

    - name: Fetch master
      if: github.ref != 'refs/heads/main'
      run: |
        git fetch origin main

    - name: Test with pytest
      env:
        DIFF_MASTER: ${{ github.event_name == 'pull_request' }}
        DIFF_LAST_COMMIT: ${{ github.ref == 'refs/heads/main' }}
      run: |
        source activate snakemake
        pytest test.py -vv
