name: Tests wrappers

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * 0'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: OS update
      run: |
        sudo apt-get update

    - name: conda/mamba
      uses: mamba-org/setup-micromamba
      with:
          create-args: |
              python=${{ matrix.python }}
              snakemake-minimal
              pytest
          condarc: |
              channels:
                  - conda-forge
                  - bioconda
              channel_priority: strict

    - name: Install dependencies
      shell: bash -l {0}
      run: |
          mamba create --quiet -y --name snakemake snakemake-minimal pytest

    - name: Fetch main
      shell: bash -l {0}
      if: github.ref != 'refs/heads/main'
      run: |
        git fetch origin main

    - name: Test with pytest
      shell: bash -l {0}
      env:
        DIFF_MASTER: ${{ github.event_name == 'pull_request' }}
        DIFF_LAST_COMMIT: ${{ github.ref == 'refs/heads/main' }}
      run: |
        source activate snakemake
        pytest test.py -vv
